version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "80:80"

  # add after make react env
  # backend:
  #   image: your-backend-image
  #   container_name: backend
