# ===== build stage =====
FROM node:20-alpine AS build

WORKDIR /app
COPY frontend/package*.json ./
RUN npm ci

COPY frontend .
RUN npm run build

# ===== runtime stage =====
FROM nginx:alpine

# nginx 設定
COPY docker/nginx/default.conf /etc/nginx/conf.d/default.conf

# build成果物
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
